name: burger_shop
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  #state management
  flutter_bloc: ^8.1.6
  bloc: ^8.1.4

  #remote data
  firebase_core: ^3.6.0 
  cloud_firestore: ^5.5.0
  firebase_auth: ^5.3.1
  firebase_storage: ^12.3.2
  google_sign_in: ^6.2.1

  #local data
  shared_preferences: ^2.0.17

  #DI
  get_it: ^7.2.0

  # navigation
  go_router: ^6.0.5

  # Functional programming thingies
  dartz: ^0.10.1
  equatable: ^2.0.5
  
  #svg, icon, font
  font_awesome_flutter: ^10.7.0

  #images, gallery, video
  cached_network_image: ^3.3.1
  image_picker: ^0.8.4+8

  device_preview: ^1.2.0
  intl_phone_number_input: ^0.7.4
  

  #SwipeableButtonAnimation
  swipeable_button_view: ^0.0.2
  page_transition: ^2.1.0
  lottie: ^3.1.2

  flutter_screenutil: ^5.9.0
  pin_code_fields: ^8.0.1
  top_snackbar_flutter: ^3.1.0

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/payment_card/
    
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
