// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOPtjpVPkvaUBb-6faFrxPY8sXYKvIa9M',
    appId: '1:960652711395:web:5c2d4c9373260eb24fbcd6',
    messagingSenderId: '960652711395',
    projectId: 'burgershop-aa859',
    authDomain: 'burgershop-aa859.firebaseapp.com',
    storageBucket: 'burgershop-aa859.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAk5I6P-xvU2Cu7vKx0qwbOLCDyLs6Mihk',
    appId: '1:960652711395:android:cd972b754066254f4fbcd6',
    messagingSenderId: '960652711395',
    projectId: 'burgershop-aa859',
    storageBucket: 'burgershop-aa859.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLOl-EL73-f40q-RR1Vf6LIH3dLp6BnZY',
    appId: '1:960652711395:ios:54e307be83e8b9ab4fbcd6',
    messagingSenderId: '960652711395',
    projectId: 'burgershop-aa859',
    storageBucket: 'burgershop-aa859.firebasestorage.app',
    iosBundleId: 'com.example.burgerShop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCLOl-EL73-f40q-RR1Vf6LIH3dLp6BnZY',
    appId: '1:960652711395:ios:54e307be83e8b9ab4fbcd6',
    messagingSenderId: '960652711395',
    projectId: 'burgershop-aa859',
    storageBucket: 'burgershop-aa859.firebasestorage.app',
    iosBundleId: 'com.example.burgerShop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAOPtjpVPkvaUBb-6faFrxPY8sXYKvIa9M',
    appId: '1:960652711395:web:7ff1026adb19d4744fbcd6',
    messagingSenderId: '960652711395',
    projectId: 'burgershop-aa859',
    authDomain: 'burgershop-aa859.firebaseapp.com',
    storageBucket: 'burgershop-aa859.firebasestorage.app',
  );
}
